// Generated by gencpp from file usonic_sensor/UInt32Stamped.msg
// DO NOT EDIT!


#ifndef USONIC_SENSOR_MESSAGE_UINT32STAMPED_H
#define USONIC_SENSOR_MESSAGE_UINT32STAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace usonic_sensor
{
template <class ContainerAllocator>
struct UInt32Stamped_
{
  typedef UInt32Stamped_<ContainerAllocator> Type;

  UInt32Stamped_()
    : header()
    , range(0)  {
    }
  UInt32Stamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , range(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _range_type;
  _range_type range;




  typedef boost::shared_ptr< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> const> ConstPtr;

}; // struct UInt32Stamped_

typedef ::usonic_sensor::UInt32Stamped_<std::allocator<void> > UInt32Stamped;

typedef boost::shared_ptr< ::usonic_sensor::UInt32Stamped > UInt32StampedPtr;
typedef boost::shared_ptr< ::usonic_sensor::UInt32Stamped const> UInt32StampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::usonic_sensor::UInt32Stamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace usonic_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'usonic_sensor': ['/home/dlr/ros_indigo/catkin_ws/src/usonic_sensor/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9edb50358deb665aa50acc5532385f48";
  }

  static const char* value(const ::usonic_sensor::UInt32Stamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9edb50358deb665aULL;
  static const uint64_t static_value2 = 0xa50acc5532385f48ULL;
};

template<class ContainerAllocator>
struct DataType< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "usonic_sensor/UInt32Stamped";
  }

  static const char* value(const ::usonic_sensor::UInt32Stamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
#Range in cm\n\
uint32 range\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::usonic_sensor::UInt32Stamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.range);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct UInt32Stamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::usonic_sensor::UInt32Stamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::usonic_sensor::UInt32Stamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "range: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.range);
  }
};

} // namespace message_operations
} // namespace ros

#endif // USONIC_SENSOR_MESSAGE_UINT32STAMPED_H
